DATA_HERE SEGMENT
DATA_A DW 1 DUP(0)
DATA_B DW 1 DUP(0)

DATA_HERE ENDS

STACK_HERE SEGMENT STACK
DW 100 DUP(0)
TOP_STACK LABEL WORD
STACK_HERE ENDS

CODE_HERE SEGMENT
ASSUME CS:CODE_HERE, DS:DATA_HERE, SS:STACK_HERE
START:
MOV AX, DATA_HERE
MOV DS, AX
MOV AX, STACK_HERE
MOV SS, AX
MOV SP, OFFSET TOP_STACK

ADD AX, BX
ADC BX, ES:[SI]
TEST AX, 0305H
MOV AX, 0305H
MUL AX
MOV DS:[BP+2h], DX
MOV DS:[DI+0203h], BX
AND AL, CH
OR AH, 03h
ROL AX, CL

INT 3H
CODE_HERE ENDS
END START